CREATE TABLE IF NOT EXISTS records (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	user_name VARCHAR(255) NOT NULL,
	meeting_id BIGINT NOT NULL,
	text TEXT NOT NULL,
	recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	end_recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_info (
	id SERIAL PRIMARY KEY,
	discord_id VARCHAR(64) NOT NULL UNIQUE,
	email VARCHAR(255),
	username VARCHAR(255),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);